services:
  backend:
    build: ./flask
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./flask:/app
    command: python -m flask run --host=0.0.0.0 --port=5000
    environment:
      - DATABASE_URL=postgresql://wca:wcapass@db:5432/wcadata
    depends_on:
      db:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: wca
      POSTGRES_PASSWORD: wcapass
      POSTGRES_DB: wcadata
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wca -d wcadata"]
      interval: 5s
      timeout: 5s
      retries: 10

  flyway:
    image: flyway/flyway:10
    command: -url=jdbc:postgresql://db:5432/wcadata -user=wca -password=wcapass -baselineOnMigrate=true -baselineVersion=1 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: {}

  